remote_theme: "mmistakes/minimal-mistakes@main"

title: Documentation
description: this is the official documentation on how to use this repo.

theme:
  name: minimal-mistakes
  color_scheme: dark

# Additional configurations if needed
